name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore
      run: dotnet restore Dotnet_test/Dotnet_test.csproj

    - name: Build
      run: dotnet build Dotnet_test/Dotnet_test.csproj --configuration Release --no-restore

    - name: Lint
      run: dotnet format Dotnet_test/Dotnet_test.csproj --verify-no-changes
