name: .NET CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check .NET SDK
        run: dotnet --version

      - name: Restore
        run: dotnet restore Dotnet_test.csproj

      - name: Build
       run: dotnet build Dotnet_test.csproj --configuration Release --no-restore